import { Inter, Noto_Kufi_Arabic } from "next/font/google";
import "../globals.css";
import Header from "@/components/Header";
import GlobalProviders from "@/components/GlobalProviders";
import Footer from "@/components/Footer";
import { NextIntlClientProvider } from "next-intl";
import {getMessages} from 'next-intl/server';
import { Toaster } from "@/components/ui/toaster";
import { getFooter, getGlobal, getMenuData } from "@/lib/getHome";
import { GoogleTagManager } from '@next/third-parties/google' 

const inter = Inter({ subsets: ["latin"] ,
  weight: ['300', '400', '500', '600', '700']});

const fontArab = Noto_Kufi_Arabic({
  subsets: ['arabic'],
  variable: '--ff-primary',
  weight: ['300', '400', '500', '600', '700']
});



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }; 

export default async function RootLayout({
  children,
  params: { session,lang, ...params },
}) {
  const messages = await getMessages();
  const [locale, country] = lang.split('-');
  const data = await getGlobal(locale, country);
  const footerData = await getFooter(locale, country);
  const menuData = await getMenuData(locale, country);
  const direction = locale === "ar" ? "rtl" : "ltr";


  return (
    <html lang={locale} dir={direction}>
      <body className={locale === "ar" ? fontArab.className : inter.className}>
      <GoogleTagManager gtmId="GTM-TR3CTMHB" />
      <NextIntlClientProvider messages={messages}>
        <GlobalProviders session={session} >
            <Header data={data} menu={menuData?.data}/>
            {children}
            <Footer data={data} menu={footerData?.data}/>
            <Toaster />
        </GlobalProviders>
        </NextIntlClientProvider>
      </body>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TR3CTMHB"
height="0" width="0" style={{ display: "none", visibility: "hidden" }}></iframe></noscript>
    </html>
  );
}
